-- #5 Magnitude (Compare the measure values by categories)

-- Find total customers by countries
SELECT 
country,
COUNT(DISTINCT customer_key) AS customers
FROM dim_customers
GROUP BY country
ORDER BY 2 DESC
;


-- Find total customers by gender
SELECT 
gender,
COUNT(customer_key) AS customers
FROM dim_customers
GROUP BY 1
ORDER BY 2 DESC
;

-- Find total products by category
SELECT 
category,
COUNT(DISTINCT product_key) AS products
FROM dim_products
GROUP BY 1
ORDER BY 2 DESC
;

-- What is the average costs in each category?
SELECT 
category,
ROUND(AVG(cost), 2) AS average_cost
FROM dim_products
GROUP BY 1
ORDER BY 2 DESC
;


-- What is the total revenue generated for each category?
SELECT
p.category,
(CASE WHEN SUM(s.sales_amount) > 0 THEN SUM(s.sales_amount) ELSE 0 END) AS total_revenue
FROM dim_products p
LEFT JOIN fact_sales s
ON p.product_key = s.product_key
WHERE category IS NOT Null
GROUP BY 1
ORDER BY 2 DESC
;


-- Find total revenue is generated by each customer
SELECT 
c.customer_key,
c.first_name,
SUM(s.sales_amount) AS total_revenue
FROM dim_customers c
LEFT JOIN fact_sales s
ON c.customer_key = s.customer_key
GROUP BY 1,2
ORDER BY 3 DESC
;


-- What is the distribution of sold items across countries?
SELECT
c.country,
SUM(s.sales_amount) AS total_revenue,
ROUND(SUM(s.quantity) * 100/(SELECT SUM(quantity) FROM fact_sales), 2) AS per_share_items_sold
FROM dim_customers c
LEFT JOIN fact_sales s
ON c.customer_key = s.customer_key
GROUP BY 1
ORDER BY 2 DESC
;
